# version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx 
    ports:
      - "443:443"
    networks:
      - wp-network
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - wp-network
    env_file:
      - .env
    restart: always
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - wp-network
    env_file:
      - .env
    volumes:
      - mariadb:/data
    restart: always
volumes:
  wordpress:
    name : wordpress
    driver: local
    driver_opts:
      type: none
      device: /${HOME}/data/wordpress
      o: bind
  mariadb:
    name : mariadb
    driver: local
    driver_opts:
      type: none
      device: /${HOME}/data/mariadb
      o: bind
  portainer:
    name : portainer
    driver: local
    driver_opts:
      type: none
      device: /${HOME}/data/portainer
      o: bind
networks:
  wp-network:
    driver: bridge